
/**
 * 加载模块配置代码
 */
"use strict";
var pathL={
    build_css:'../build',     //gulp 编译之后的路径
    //build_css:'..'           //原始路径
};
app.constant("Modules_Config",[
    {
        name:"home_Res",
        module:true,
        files:[
            /*"../content/bootstrap.min.css",
             "../scripts/layer/need/layer.css",*/
            ""+pathL.build_css+"/css/_layout.css?V=0.99922",
            /*"../scripts/jquery.cookie.js",*/
            /*  "../scripts/layer/layer.js",*/
            "../js/helpTool.js?v=0.00012111"
        ]
    },
    {
        name:"illegaQuery_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/illegaQuery.css",
            ""+pathL.build_css+"/css/LArea.css",
            "../js/tool/LAreaData1.js",
            "../js/tool/LArea.js"
        ]
    },
    {
        name:"illegaDetail_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/illegaDetail.css"
        ]
    },
    {
        name:'illegaInfor_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/illegaInfor.css"
        ]
    },
    {
        name:"carButler_Res",
        module:true,
        files:[
            "../scripts/swipe/css/swiper.min.css",
            ""+pathL.build_css+"/css/carButler.css?v=0.000001",
            {type:'js',path:"http://webapi.amap.com/maps?v=1.3&key=41f5a3e38b89fac5db6bd4a6961aeabd"},
            "../scripts/swipe/js/swiper.min.js",
            "../js/adapt/carButlerAdapt.js"
        ]
    },
    {
        name:"gasCard_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/gasCard.css",
            "../js/tool/gasCard.js"
        ]
    },
    {
        name:"addCarType_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/addCarType.css"
        ]
    },
    {
        name:"login_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/register.css"
        ]
    },
    {
        name:"register_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/register.css"
        ]
    },
    {
        name:"cleanCar_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/cleanCar.css"
        ]
    },
    {
        name:"orderRecord_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/orderRecord.css"
        ]
    },
    {
        name:"rentCar_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/rentCar.css"
        ]
    },
    {
        name:"replaceStop_Res",
        module:true,
        files:[
            "../content/mobiscroll-2.13.2.full.min.css",
            ""+pathL.build_css+"/css/jianPan.css",
            ""+pathL.build_css+"/css/replaceStop.css?V=0.0005",
            {type:'js',path:"http://webapi.amap.com/maps?v=1.3&key=41f5a3e38b89fac5db6bd4a6961aeabd"},
            "../scripts/mobiscroll-2.13.2.full.min.js"
        ]
    },
    {
        name:"replaceOrder_Res",
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css?V=1.0.7",
            "../scripts/swipe/css/swiper.min.css",
            ""+pathL.build_css+"/css/replaceOrder.css?V=1.0.7",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js",
            "../js/tool/pic.js",
            "../scripts/swipe/js/swiper.min.js"
        ]
    },
    {
        name:'orderAssess_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/base.css",
            ""+pathL.build_css+"/css/orderAssess.css"
        ]
    },
    {
        name:'chart_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/chart.css",
            "../js/tool/highcharts.js",
            /* "../scripts/iscroll.js"*/
            /*"../scripts/iscroll-probe.js"*/
        ]
    },
    {
        name:'proChart_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/proChart.css",
            "../js/tool/highcharts.js",
            "../scripts/iscroll.js"
        ]
    },
    {
        name:'report_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/report.css",
            '../js/tool/highcharts.js'
        ]
    },
    {
        name:'actOne_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actOne.css",
            /*"http://res.wx.qq.com/open/js/jweixin-1.0.0.js",*/
            "../js/adapt/actOneAdapt.js"
        ]
    },
    {
        name:'actTwo_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actTwo.css",
        ]

    },
    {
        name:'actFive_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actFive.css",
        ]
    },
    {
        name:'actSix_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actSix.css",
        ]

    },
    {
        name:'actThree_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actThree.css",
        ]
    },
    {
        name:'actFour_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actFour.css",
        ]
    },
    {
        name:'actSeven_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actSeven.css",
        ]
    },
    {
        name:'actEight_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/actEight.css",
        ]

    },
    {
        name:'invit_Res',
        module:true,
        files:[
            "../content/mobiscroll-2.13.2.full.min.css",
            ""+pathL.build_css+"/css/invit.css",
            "../scripts/mobiscroll-2.13.2.full.min.js"
        ]
    },
    {
        name:'invitCred_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/invitCred.css",
        ]
    },
    {
        name:'parkPay_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/parkPay.css",
             ""+pathL.build_css+"/css/jianPan.css",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js",
        ]
    },
    {
        name:'paySuccess_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/paySuccess.css",
        ]
    },
    {
        name:'payOrder_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/payOrder.css",
        ]
    },
    {
        name:'payAgree_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/payAgree.css"

        ]
    },
    {
        name:'reservedPark_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/reservedPark.css",
            {type:'js',path:"http://webapi.amap.com/maps?v=1.3&key=41f5a3e38b89fac5db6bd4a6961aeabd"},
            "../scripts/iscroll.js",
            "../js/adapt/reservedParkAdapt.js"
        ]
    },
    {
        name:'reservedParkOrder_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/reservedParkOrder.css",
            "../scripts/iscroll.js",
            "../js/adapt/reservedParkAdapt.js",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js",
        ]
    },
    {
        name:'reservedOrder_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/payOrder.css",
            "../scripts/jquery.qrcode.min.js",
            "../scripts/jquery-barcode.js"
        ]
    },
    {
        name:'scanPark_Res',
        module:true,
        files:[
            "../content/mobiscroll-2.13.2.full.min.css",
            ""+pathL.build_css+"/css/replaceStop.css?V=0.0005",
            /* {type:'js',path:"http://webapi.amap.com/maps?v=1.3&key=41f5a3e38b89fac5db6bd4a6961aeabd"},*/
            "../scripts/mobiscroll-2.13.2.full.min.js"
        ]
    },
    {
        name:'payNumber_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/payNumber.css",
            /*"../js/adapt/reservedParkAdapt.js",*/
        ]
    },
    {
        name:'monthPay_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/monthPay.css",
            ""+pathL.build_css+"/css/jianPan.css",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js"
        ]
    },
    {
        name:'propertyPay_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/propertyPay.css",
            ""+pathL.build_css+"/css/jianPan.css",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js"
        ]
    },
    {
        name:'temPay_Res',
        module:true,
        files:[
            ""+pathL.build_css+"/css/temPay.css",
            "http://res.wx.qq.com/open/js/jweixin-1.0.0.js"
        ]
    },
    {
        name:'activePark_Res',
        module:true,
        files: [
            "../js/adapt/reserverParkAdapt_V2.js",
            ""+pathL.build_css+"/css/activePark.css"
        ]
    },
    {
      name:'activeParkReg_Res',
        module:true,
        files: [
            "../js/adapt/reserverParkAdapt_V2.js",
            ""+pathL.build_css+"/css/activePark.css"
        ]
    },
    {
        name:'activeParkfail_Res',
        module:true,
        files: [
            ""+pathL.build_css+"/css/activeParkfail.css",
            "../js/adapt/reserverParkAdapt_V2.js"
        ]
    }
]);
app.config(["$ocLazyLoadProvider","Modules_Config",routeFnLoad]);
function routeFnLoad($ocLazyLoadProvider,Modules_Config){
    $ocLazyLoadProvider.config({
        debug:false,
        events:false,
        modules:Modules_Config
    })
};

